// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQB4KoUxX0cJI5G7beuzFxB3IEwXGTIA',
    appId: '1:71714348040:web:7bc7ad3914cf42f30585bd',
    messagingSenderId: '71714348040',
    projectId: 'minito-users',
    authDomain: 'minito-users.firebaseapp.com',
    storageBucket: 'minito-users.firebasestorage.app',
    measurementId: 'G-LZHTJ1QXV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsskm3BBY1TQSLJlVTH0-Oeb1LUzfUUs',
    appId: '1:71714348040:android:4ff7a807c5d87f5f0585bd',
    messagingSenderId: '71714348040',
    projectId: 'minito-users',
    storageBucket: 'minito-users.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Aqvl7Qhq_3_8dD_8PN4MbD3_ghqVdJI',
    appId: '1:71714348040:ios:aafd6feff25146ae0585bd',
    messagingSenderId: '71714348040',
    projectId: 'minito-users',
    storageBucket: 'minito-users.firebasestorage.app',
    iosBundleId: 'com.example.miniRobo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Aqvl7Qhq_3_8dD_8PN4MbD3_ghqVdJI',
    appId: '1:71714348040:ios:aafd6feff25146ae0585bd',
    messagingSenderId: '71714348040',
    projectId: 'minito-users',
    storageBucket: 'minito-users.firebasestorage.app',
    iosBundleId: 'com.example.miniRobo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpQB4KoUxX0cJI5G7beuzFxB3IEwXGTIA',
    appId: '1:71714348040:web:a52b24fd6b12d0110585bd',
    messagingSenderId: '71714348040',
    projectId: 'minito-users',
    authDomain: 'minito-users.firebaseapp.com',
    storageBucket: 'minito-users.firebasestorage.app',
    measurementId: 'G-77Q65VZKRW',
  );
}
